[package]
name = "easybitflags"
version = "0.1.0"
edition = "2024"
[lib]
name = "easybitflags"

[dependencies]
flags_derive = { path = "./flags_derive" }

[workspace]
resolver = "2"
members = ["flags_derive"]
